<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Adds Serilog destructuring support for Smart Enums, Value Objects and Ad-hoc Unions from Thinktecture.Runtime.Extensions.</Description>
    <PackageTags>smart-enum;value-object;discriminated-union;serilog;logging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" VersionOverride="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thinktecture.Runtime.Extensions\Thinktecture.Runtime.Extensions.csproj" />

    <ProjectReference Include="..\..\src\Thinktecture.Runtime.Extensions.SourceGenerator\Thinktecture.Runtime.Extensions.SourceGenerator.csproj"
                      SetTargetFramework="TargetFramework=netstandard2.0"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer" />
    <ProjectReference Include="..\Thinktecture.Runtime.Extensions.Refactorings\Thinktecture.Runtime.Extensions.Refactorings.csproj"
                      SetTargetFramework="TargetFramework=netstandard2.0"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
