namespace Thinktecture.CodeAnalysis;

public abstract class CodeGeneratorBase
{
   internal const string GENERATED_CODE_PREFIX = @"// <auto-generated />
#nullable enable";

   public abstract string? FileNameSuffix { get; }
   public abstract void Generate(CancellationToken cancellationToken);
}
