namespace Thinktecture.CodeAnalysis;

public abstract class CodeGeneratorBase
{
   public const string GENERATED_CODE_PREFIX = @"// <auto-generated />
#nullable enable";

   public abstract string? FileNameSuffix { get; }
   public abstract string? Generate();
}
