namespace Thinktecture.CodeAnalysis;

internal static class DiagnosticsDescriptors
{
   public static readonly DiagnosticDescriptor FieldMustBeReadOnly = new("TTRESG001", "Field must be read-only", "The field '{0}' of the type '{1}' must be read-only", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SmartEnumItemMustBePublic = new("TTRESG002", "Smart Enum item must be public", "The Smart Enum item '{0}' of the type '{1}' must be public", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor PropertyMustBeReadOnly = new("TTRESG003", "Property must be read-only", "The property '{0}' of the type '{1}' must be read-only", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustBeClassOrStruct = new("TTRESG004", "The type must be a class or a struct", "The type '{0}' must be a class or a struct", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustBePartial = new("TTRESG006", "Type must be partial", "The type '{0}' must be partial", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ConstructorsMustBePrivate = new("TTRESG009", "The constructors must be private", "All constructors of type '{0}' must be private", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SmartEnumKeyMemberNameNotAllowed = new("TTRESG012", "Provided key member name is not allowed", "Provided key member name '{0}' is not allowed", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor InnerSmartEnumOnFirstLevelMustBePrivate = new("TTRESG014", "Inner Smart Enum on first level must be private", "Derived inner Smart Enum '{0}' on first-level must be private", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor InnerSmartEnumOnNonFirstLevelMustBePublic = new("TTRESG015", "Inner Smart Enum on non-first level must be public", "Derived inner Smart Enum '{0}' on non-first-level must be public", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor KeyMemberShouldNotBeNullable = new("TTRESG017", "The key member must not be nullable", "A key member must not be nullable", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor BaseClassFieldMustBeReadOnly = new("TTRESG034", "Field of the base class must be read-only", "The field '{0}' of the base class '{1}' must be read-only", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor BaseClassPropertyMustBeReadOnly = new("TTRESG035", "Property of the base class must be read-only", "The property '{0}' of the base class '{1}' must be read-only", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SmartEnumKeyShouldNotBeNullable = new("TTRESG036", "The key type must not be nullable", "The generic type T of SmartEnumAttribute<T> must not be nullable", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SmartEnumWithoutDerivedTypesMustBeSealed = new("TTRESG037", "Smart Enum without derived types must be sealed", "Smart Enum '{0}' without derived types must be sealed", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ComparerTypeMustMatchMemberType = new("TTRESG041", "The type of the comparer doesn't match the type of the member", "The comparer '{0}' doesn't match the member type '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor InitAccessorMustBePrivate = new("TTRESG042", "Property 'init' accessor must be private", "The 'init' accessor of the property '{0}' of the type '{1}' must be private", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor PrimaryConstructorNotAllowed = new("TTRESG043", "Primary constructor is not allowed", "Primary constructor is not allowed in object of type '{0}' because it cannot be marked as 'private'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor CustomKeyMemberImplementationNotFound = new("TTRESG044", "Custom implementation of the key member not found", $"Provide a custom implementation of the key member. Implement a field or property '{{0}}'. Use '{Constants.Attributes.Properties.KEY_MEMBER_NAME}' to change the name.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor CustomKeyMemberImplementationTypeMismatch = new("TTRESG045", "Key member type mismatch", "The type of the key member '{0}' must be '{2}' instead of '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor IndexBasedSwitchAndMapMustUseNamedParameters = new("TTRESG046", "The arguments of 'Switch' and 'Map' must be named", "Not all arguments of 'Switch/Map' on type '{0}' are named", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor VariableMustBeInitializedWithNonDefaultValue = new("TTRESG047", "Variable must be initialed with non-default value", "Variable of type '{0}' must be initialized with non-default value", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor StringBasedValueObjectNeedsEqualityComparer = new("TTRESG048", "String-based Value Object needs equality comparer", "String-based Value Object needs equality comparer. Use 'KeyMemberEqualityComparerAttribute<TAccessor, TKey>' to define the equality comparer. Example: [KeyMemberEqualityComparer<ComparerAccessors.StringOrdinalIgnoreCase, string>].", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor ComplexValueObjectWithStringMembersNeedsDefaultEqualityComparer = new("TTRESG049", "Complex Value Object with string members needs equality comparer", "Complex Value Object with string members needs equality comparer. Use 'DefaultStringComparison' to define the comparer. Example: [ComplexValueObject(DefaultStringComparison = StringComparison.OrdinalIgnoreCase)].", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor MethodWithUseDelegateFromConstructorMustBePartial = new("TTRESG050", $"Method with '{Constants.Attributes.UseDelegateFromConstructor.NAME}' must be partial", $"The method '{{0}}' with '{Constants.Attributes.UseDelegateFromConstructor.NAME}' must be marked as partial", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor MethodWithUseDelegateFromConstructorMustNotHaveGenerics = new("TTRESG051", $"Method with '{Constants.Attributes.UseDelegateFromConstructor.NAME}' must not have generics", $"The method '{{0}}' with '{Constants.Attributes.UseDelegateFromConstructor.NAME}' must not have generic type parameters. Use inheritance approach instead.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor UnionDerivedTypesMustNotBeGeneric = new("TTRESG053", "Derived type of a union must not be generic", "Derived type '{0}' of a union must not be generic", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor UnionMustBeSealedOrHavePrivateConstructorsOnly = new("TTRESG054", "Discriminated union must be sealed or have private constructors only", "Discriminated union '{0}' must be sealed or have private constructors only", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor UnionRecordMustBeSealed = new("TTRESG055", "Discriminated union implemented using a record must be sealed", "Discriminated union '{0}' using a record must be sealed. Use a class for nesting unions.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor NonAbstractDerivedUnionIsLessAccessibleThanBaseUnion = new("TTRESG056", "Non-abstract derived union is less accessible than base union", "Non-abstract derived union '{0}' is less accessible than base union '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AllowDefaultStructsCannotBeTrueIfValueObjectIsStructButKeyTypeIsClass = new("TTRESG057", "'AllowDefaultStructs' must be 'false' if Value Object is a struct but key type is a reference type", "'AllowDefaultStructs' of type '{0}' must be 'false' because it is a struct but the key type '{1}' is a reference type", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AllowDefaultStructsCannotBeTrueIfSomeMembersDisallowDefaultValues = new("TTRESG058", "'AllowDefaultStructs' must be 'false' if some members disallow default values", "'AllowDefaultStructs' of type '{0}' must be 'false' because following members disallow default values: {1}", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ObjectFactoryMustHaveCorrespondingConstructor = new("TTRESG059", "Type with ObjectFactoryAttribute<T> and 'HasCorrespondingConstructor = true' must have a constructor with type 'T'", "The type '{0}' with 'ObjectFactoryAttribute<{1}>' and 'HasCorrespondingConstructor = true' must have a constructor with a single argument of type '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SmartEnumMustNotHaveObjectFactoryConstructor = new("TTRESG060", "Smart Enums with ObjectFactoryAttribute<T> must not have 'HasCorrespondingConstructor' set to 'true'", "Smart Enum '{0}' with 'ObjectFactoryAttribute<{1}>' must not have the property 'HasCorrespondingConstructor' set to 'true'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ObjectFactoryMustImplementStaticValidateMethod = new("TTRESG061", "Type with ObjectFactoryAttribute<TValue> must implement static Validate method", "The type '{0}' with 'ObjectFactoryAttribute<{2}>' must implement a static method 'Validate' with signature: static {4}? Validate({3} value, IFormatProvider? provider, out {1} item)", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ObjectFactoryMustImplementToValueMethod = new("TTRESG062", "Type with ObjectFactoryAttribute<TValue> must implement ToValue method when used for serialization or Entity Framework", "The type '{0}' with 'ObjectFactoryAttribute<{1}>' must implement an instance method '{1} ToValue()' because 'UseForSerialization' is not 'None' or 'UseWithEntityFramework' is 'true'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustNotHaveMoreThanOneAttribute = new("TTRESG063", "Type must not have more than one ValueObject/SmartEnum/Union-attribute", "The type '{0}' must not have more than one ValueObject/SmartEnum/Union-attribute", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustNotHaveMoveThanOneSmartEnumAttribute = new("TTRESG064", $"Type must not have more than one {Constants.Attributes.SmartEnum.NAME}", $"The type '{{0}}' must not have more than one {Constants.Attributes.SmartEnum.NAME}", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustNotHaveMoveThanOneValueObjectAttribute = new("TTRESG065", $"Type must not have more than one {Constants.Attributes.ValueObject.KEYED_NAME}/{Constants.Attributes.ValueObject.COMPLEX_NAME}", $"The type '{{0}}' must not have more than one {Constants.Attributes.ValueObject.KEYED_NAME}/{Constants.Attributes.ValueObject.COMPLEX_NAME}", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeMustNotHaveMoveThanOneDiscriminatedUnionAttribute = new("TTRESG066", $"Type must not have more than one {Constants.Attributes.Union.NAME}/{Constants.Attributes.Union.NAME_AD_HOC}", $"The type '{{0}}' must not have more than one {Constants.Attributes.Union.NAME}/{Constants.Attributes.Union.NAME_AD_HOC}", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AdHocUnionMustHaveAtLeastTwoMemberTypes = new("TTRESG067", "Ad hoc union must define at least two member types", "Ad hoc union '{0}' must have at least two member types", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor MultipleObjectFactoryAttributesWithUseWithEntityFramework = new("TTRESG068", "Multiple ObjectFactoryAttribute instances cannot have UseWithEntityFramework = true", "Type '{0}' has multiple ObjectFactoryAttribute instances with 'UseWithEntityFramework = true'. Only one ObjectFactoryAttribute can have 'UseWithEntityFramework = true'.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor MultipleObjectFactoryAttributesWithUseForModelBinding = new("TTRESG069", "Multiple ObjectFactoryAttribute instances cannot have UseForModelBinding = true", "Type '{0}' has multiple ObjectFactoryAttribute instances with 'UseForModelBinding = true'. Only one ObjectFactoryAttribute can have 'UseForModelBinding = true'.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor MultipleObjectFactoryAttributesWithOverlappingSerializationFrameworks = new("TTRESG070", "Multiple ObjectFactoryAttribute instances cannot specify overlapping serialization frameworks", "Type '{0}' has multiple ObjectFactoryAttribute instances with overlapping serialization frameworks '{1}'. Each serialization framework can only be used by one ObjectFactoryAttribute.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeParamRefIndexOutOfRange = new("TTRESG071", "TypeParamRef index exceeds the number of type parameters", "TypeParamRef{0} references type parameter at index {0}, but the type '{1}' has only {2} type parameter(s)", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeParamRefOnNonGenericUnion = new("TTRESG072", "TypeParamRef cannot be used on non-generic type", "TypeParamRef{0} cannot be used on non-generic type '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AllowsRefStructNotSupportedOnAdHocUnion = new("TTRESG073", "Ad-hoc unions do not support 'allows ref struct' type parameters", "Ad-hoc union '{0}' has type parameter '{1}' with 'allows ref struct' which is not supported. Remove the 'allows ref struct' anti-constraint from the type parameter.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor TypeParamRefRequiresNotnullConstraint = new("TTRESG074", "Type parameter used via TypeParamRef must have 'notnull' constraint", "The type parameter '{0}' of type '{1}' is used as a key type via TypeParamRef and must have a 'notnull' constraint", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor SingleBackingFieldTypeConflictsWithUseSingleBackingField = new("TTRESG075", "'SingleBackingFieldType' conflicts with 'UseSingleBackingField = false'", "Type '{0}' has 'SingleBackingFieldType' set together with 'UseSingleBackingField = false'. Setting 'SingleBackingFieldType' implies 'UseSingleBackingField = true'. Remove 'UseSingleBackingField = false' or unset 'SingleBackingFieldType'.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ValidateFactoryArgumentsAdditionalParameterMustNotHaveDefaultOrBeByRef = new("TTRESG076", "Additional 'ValidateFactoryArguments' parameter must not be 'ref'/'out' or have a default value", "The additional parameter '{0}' of 'ValidateFactoryArguments' on type '{1}' must not be 'ref'/'out' and must not declare a default value. The source generator supplies the default on its own declaration; a default here has no effect (CS1066).", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AdHocUnionMemberTypeIsLessAccessibleThanUnion = new("TTRESG077", "Ad-hoc union member type is less accessible than the union", "The member type '{0}' is less accessible than the ad-hoc union '{1}'. The generated conversion operators, 'As' properties, 'Switch'/'Map' overloads, constructors and factory methods expose '{0}' and therefore cannot compile (CS0051/CS0053). Either lower the accessibility of '{1}' or raise the accessibility of '{0}'.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor RefStructObjectFactoryMustNotBeUsedWithEntityFrameworkOrModelBinding = new("TTRESG078", "Object factories with a ref struct value type must not enable 'UseWithEntityFramework' or 'UseForModelBinding'", "The type '{0}' has an object factory whose value type is a ref struct with '{1} = true'. A ref struct cannot be used as the generic value type argument required by Entity Framework Core value converters and ASP.NET Core model binding, so this configuration fails at runtime. Remove '{1} = true' or use a non-ref-struct value type for this factory.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AdHocUnionMemberTypeNotConvertibleToSingleBackingFieldType = new("TTRESG079", "Ad-hoc union member type is not implicitly convertible to 'SingleBackingFieldType'", "The member type '{0}' of the ad-hoc union '{1}' cannot be stored in the backing field of type '{2}'. Every member type needs a built-in implicit conversion (identity, reference, boxing, or value conversion) to the 'SingleBackingFieldType'; user-defined conversions are not supported because the stored value must remain the original instance. Use a common base class or interface, or remove 'SingleBackingFieldType'.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor AllowDefaultStructsCannotBeTrueIfTypeImplementsIDisallowDefaultValue = new("TTRESG080", $"'AllowDefaultStructs' must be 'false' if the type implements '{Constants.Interfaces.IDisallowDefaultValue.NAME}'", $"'AllowDefaultStructs' of type '{{0}}' must be 'false' because the type implements '{Constants.Interfaces.IDisallowDefaultValue.NAME}', which disallows the default value", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor DefaultValueHandlingMapToFirstMemberRequiresStructUnion = new("TTRESG081", "'DefaultValueHandling = MapToFirstMember' requires a struct union", "The ad-hoc union '{0}' is a reference type, so 'DefaultValueHandling = MapToFirstMember' has no effect. The setting maps the default value of a struct union to its first member. Change the union to a struct or remove the setting.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor DefaultValueHandlingMapToFirstMemberRequiresStatelessFirstMember = new("TTRESG082", "'DefaultValueHandling = MapToFirstMember' requires a stateless first member", "The ad-hoc union '{0}' uses 'DefaultValueHandling = MapToFirstMember', but its first member (T1) is not stateless. The default value carries no state, so the first member must be stateless. Set 'T1IsStateless = true' or remove the setting.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);

   public static readonly DiagnosticDescriptor ErrorDuringModulesAnalysis = new("TTRESG097", "Error during analysis of referenced modules", "Error during analysis of referenced modules: '{0}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);
   public static readonly DiagnosticDescriptor ErrorDuringCodeAnalysis = new("TTRESG098", "Error during code analysis", "Error during code analysis of '{0}': '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor ErrorDuringGeneration = new("TTRESG099", "Error during code generation", "Error during code generation for '{0}': '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Error, true);

   public static readonly DiagnosticDescriptor SmartEnumHasNoItems = new("TTRESG100", "The Smart Enum has no items", "The Smart Enum '{0}' has no items", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor StaticPropertiesAreNotConsideredItems = new("TTRESG101", "Static properties are not considered Smart Enum items, use a field instead", "The static property '{0}' is not considered a Smart Enum item, use a field instead", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor ExplicitComparerWithoutEqualityComparer = new("TTRESG102", "The type has a comparer defined but no equality comparer", "The type '{0}' has a comparer defined but no equality comparer", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor ExplicitEqualityComparerWithoutComparer = new("TTRESG103", "The type has an equality comparer defined but no comparer", "The type '{0}' has an equality comparer defined but no comparer", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor MembersDisallowingDefaultValuesMustBeRequired = new("TTRESG104", "The member must be marked as 'required' to ensure proper initialization", "The {0} '{1}' of type '{2}' must be marked as 'required' to ensure proper initialization", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor ComparisonAndEqualityOperatorsMismatch = new("TTRESG105", "Comparison and equality operators settings mismatch", "The type '{0}' has 'ComparisonOperators = {1}' and 'EqualityComparisonOperators = {2}' which differ. Set them to the same value.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor InnerTypeDoesNotDeriveFromUnion = new("TTRESG106", "Inner type should derive from union type", "The inner type '{0}' should derive from union type '{1}'", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor GenericUnionWithoutTypeParamRef = new("TTRESG107", "Generic ad-hoc union does not reference any type parameter via TypeParamRef", "Generic ad-hoc union '{0}' does not reference any type parameter via TypeParamRef. All type parameters are unused.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor RefStructObjectFactoryIgnoredBySerializationFrameworks = new("TTRESG108", "Object factory with a ref struct value type is ignored by the configured serialization frameworks", "The type '{0}' has an object factory whose value type '{1}' is a ref struct, but 'UseForSerialization' includes '{2}'. These frameworks cannot use a ref struct, so the factory is ignored and serialization falls back to the key-based conversion. Remove the flags or use a non-ref-struct value type. Only 'ReadOnlySpan<char>' with 'SerializationFrameworks.SystemTextJson' is supported.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor EmptyStringInFactoryMethodsYieldsNullHasNoEffectOnStructs = new("TTRESG109", "'EmptyStringInFactoryMethodsYieldsNull' has no effect on structs", "The type '{0}' is a struct, so 'EmptyStringInFactoryMethodsYieldsNull = true' has no effect and is ignored by the source generator, together with the implied 'NullInFactoryMethodsYieldsNull'. Remove the setting or change the type to a class.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);
   public static readonly DiagnosticDescriptor IDisallowDefaultValueHasNoEffectOnReferenceTypes = new("TTRESG110", $"'{Constants.Interfaces.IDisallowDefaultValue.NAME}' has no effect on reference types", $"The type '{{0}}' is a reference type, so implementing '{Constants.Interfaces.IDisallowDefaultValue.NAME}' has no effect. The interface only rejects the default value of value types. Remove the interface or change the type to a struct.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);

   public static readonly DiagnosticDescriptor InternalApiUsage = new("TTRESG1000", "Internal Thinktecture.Runtime.Extensions API usage", "'{0}' is an internal API that supports the Thinktecture.Runtime.Extensions infrastructure and not subject to the same compatibility standards as public APIs. It may be changed or removed without notice in any release.", Constants.INTERNAL_USAGE_ANALYZER_CATEGORY, DiagnosticSeverity.Warning, true);

   public static readonly DiagnosticDescriptor UseSwitchMapWithStaticLambda = new("TTRESG1001", "Consider using a static lambda", "Lambda passed to '{0}' should be static. Use a static lambda to avoid unnecessary allocations, or use the state overload to pass captured variables explicitly.", Constants.ANALYZER_CATEGORY, DiagnosticSeverity.Info, true);
}
