// <auto-generated />
#nullable enable

partial class TestEnum :
   global::System.Numerics.IEqualityOperators<global::TestEnum, global::TestEnum, bool>
{
      /// <summary>
      /// Compares two instances of <see cref="TestEnum"/>.
      /// </summary>
      /// <param name="obj">Instance to compare.</param>
      /// <param name="other">Another instance to compare.</param>
      /// <returns><c>true</c> if objects are equal; otherwise <c>false</c>.</returns>
      public static bool operator ==(global::TestEnum? obj, global::TestEnum? other)
      {
         return global::System.Object.ReferenceEquals(obj, other);
      }

      /// <summary>
      /// Compares two instances of <see cref="TestEnum"/>.
      /// </summary>
      /// <param name="obj">Instance to compare.</param>
      /// <param name="other">Another instance to compare.</param>
      /// <returns><c>false</c> if objects are equal; otherwise <c>true</c>.</returns>
      public static bool operator !=(global::TestEnum? obj, global::TestEnum? other)
      {
         return !(obj == other);
      }
}
