using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Thinktecture
{
   /// <summary>
   /// Source generator for JsonConverter for an enum-like class.
   /// </summary>
   [Generator]
   public class EnumJsonConverterSourceGenerator : EnumSourceGeneratorBase
   {
      /// <inheritdoc />
      protected override string GenerateCode(EnumSourceGeneratorState state)
      {
         var sb = new StringBuilder($@"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using Thinktecture;

{(String.IsNullOrWhiteSpace(state.Namespace) ? null : $"namespace {state.Namespace}")}
{{
   public class {state.EnumType}_EnumJsonConverter : Thinktecture.Text.Json.Serialization.EnumJsonConverter<{state.EnumType}, {state.KeyType}>
   {{
      [return: NotNullIfNotNull(""key"")]
      protected override {state.EnumType}{state.NullableQuestionMark} ConvertFrom({state.KeyType}{state.NullableQuestionMarkKey} key)
      {{
         return {state.EnumType}.Get(key);
      }}
   }}
");

         if (!HasJsonConverterAttribute(state))
         {
            sb.Append($@"
   [System.Text.Json.Serialization.JsonConverterAttribute(typeof({state.ClassDeclarationSyntax.Identifier}_EnumJsonConverter))]
   partial class {state.EnumType}
   {{
   }}
");
         }

         sb.Append(@"
}
");

         return sb.ToString();
      }

      private static bool HasJsonConverterAttribute(EnumSourceGeneratorState state)
      {
         return state.ClassDeclarationSyntax.AttributeLists.SelectMany(a => a.Attributes).Any(a => state.Model.GetTypeInfo(a).Type?.ToString() == "System.Text.Json.Serialization.JsonConverterAttribute");
      }
   }
}
